spring:
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: msg
    encoding: UTF-8
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/stud
    username: root
  jpa:
    hibernate:
      ddl-auto: update
